# --- Oracle DataSource ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=trajectory
spring.datasource.password=tnghks12
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# MySQL \uC804\uC6A9 \uD30C\uB77C\uBBF8\uD130(serverTimezone, characterEncoding) \uC81C\uAC70!

spring.datasource.hikari.pool-name=Hikari-Oracle
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL

# --- MyBatis ---
mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.type-aliases-package=com.Devim.backend.domain
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL

# --- Logging ---
logging.level.org.springframework.test.context.transaction=trace
logging.level.org.springframework.jdbc.core=DEBUG