spring:
  config:
    import: classpath:db-credentials.yml  # username, password만 불러옴
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.Devim.backend.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# File upload path
upload:
  path: D:\gitCode\DeVim\Kangho\backend\upload

logging:
  level:
    com.Devim: debug
    org:
      springframework:
        test:
          context:
            transaction: trace
        jdbc:
          core: debug
